CC = gcc
CFLAGS = -Wall -Wextra -std=c11
TARGETS = challenge1 challenge2 challenge3

all: $(TARGETS)

challenge1: challenge1.c
	$(CC) $(CFLAGS) -o challenge1 challenge1.c

challenge2: challenge2.c
	$(CC) $(CFLAGS) -o challenge2 challenge2.c

challenge3: challenge3.c
	$(CC) $(CFLAGS) -o challenge3 challenge3.c

clean:
	rm -f $(TARGETS)
